# @Author: Andreas Schlapbach <schlpbch>
# @Date:   2017-04-30T12:35:42+02:00
# @Email:  schlpbch@gmail.com
# @Last modified by:   schlpbch
# @Last modified time: 2017-04-30T13:56:59+02:00
# @License: ALv2

version: '2'
services:
  nginx:
    build: docker-images/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - php-fpm
    networks:
      - front-tier

  php-fpm:
    build: docker-images/php-fpm
    volumes:
      - ./prestashop/:/html/
    networks:
      - front-tier
      - back-tier

  mysql:
    build: docker-images/mysql
    hostname: db-server
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - back-tier
    environment:
      MYSQL_ROOT_PASSWORD: mysql-root-pwd
      MYSQL_USER: mysql-user
      MYSQL_PASSWORD: mysql-pwd
      MYSQL_DATABASE: prestashop

  phpadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9010:80"
    networks:
      - back-tier
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: "3306"

  # For debugging purposes only
  portainer:
    image: portainer/portainer:latest
    privileged: true
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mysql-data:
    driver: local

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
