version: '2'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./site.conf:/etc/nginx/conf.d/default.conf:ro
            - ./keys:/etc/nginx/ssl:ro

    php-fm:
        image: php:fpm
        volumes:
            - ./PrestaShop/:/html

    db:
        image: mysql:latest
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: richard4
            MYSQL_USER: schlpbch
            MYSQL_PASSWORD: richard6
            MYSQL_DATABASE: firstPrestaShop

#    ui4docker:
#        image: uifd/ui-for-docker:latest
#        privileged: true
#        ports:
#           - "9000:9000"
#        volumes:
#           - /var/run/docker.sock:/var/run/docker.sock
