# @Author: Andreas Schlapbach <schlpbch>
# @Date:   2017-04-30T12:35:42+02:00
# @Email:  andreas.schlapbach@sbb.ch
# @Last modified by:   schlpbch
# @Last modified time: 2017-04-30T13:14:19+02:00
# @License: ALv2
# @Copyright: 2017 Schweizerische Bundesbahnen (SBB)

nginx:
    build: docker-images/nginx
    ports:
        - "80:80"
        - "443:443"
    volumes_from:
       - php-fpm
    links:
      - "php-fpm:php-fpm"

php-fpm:
    build: docker-images/php-fpm
    volumes:
        - ./prestashop/:/html/
    links:
        - "mysql:mysql"

mysql:
    build: docker-images/mysql
    hostname: sql-server
    volumes:
        - ./db:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: mysql-root-pwd
        MYSQL_USER: mysql-user
        MYSQL_PASSWORD: mysql-pwd
        MYSQL_DATABASE: prestashop

portainer:
  image: portainer/portainer:latest
  privileged: true
  ports:
    - "9000:9000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock


phpadmin:
   image: phpmyadmin/phpmyadmin
   ports:
       - "9010:80"
   links:
       - "mysql:mysql"
   environment:
       PMA_HOST: "mysql"
       PMA_PORT: "3306"

#cadvisor:
#   image: google/cadvisor
#   ports:
#       - "9020:8080"
#   volumes:
#       - /:/rootfs:ro
#       - /var/run:/var/run:rw
#       - /sys:/sys:ro
#       - /var/lib/docker/:/var/lib/docker:ro
